### ISSUE TITLE
Wikipedia article seems to consider this to have websocket server functionality

### ISSUE THREAD

**Issue by ignasg** [vinniefalco/Beast#25] opened 2016-06-15 13:34 UTC
https://en.wikipedia.org/wiki/Comparison_of_WebSocket_implementations
As I only see this is a client library, probably the wikipedia article needs to be updated

**Comment by vinniefalco** [comment] 2016-06-15 15:16
Where did you get the idea that Beast only offers a WebSocket client? It has both. We use Beast in rippled, which exposes a WebSocket server for clients to issue requests:
https://github.com/ripple/rippled/blob/develop/src/ripple/server/impl/SSLWSPeer.h#L48

To implement a server, just call `beast::websocket::stream::accept` on the socket used to receive the incoming connection, and it will read the Upgrade request and respond to it appropriately:
https://github.com/vinniefalco/Beast/blob/999e2fa0318b5982736d3ea01a418770ea802671/include/beast/websocket/stream.hpp#L312

The Beast Autobahn|Testsuite report shows both the synchronous and asynchronous modes of operation, source code for those WebSocket servers are here:
https://github.com/vinniefalco/Beast/blob/999e2fa0318b5982736d3ea01a418770ea802671/test/websocket/websocket_async_echo_peer.hpp
https://github.com/vinniefalco/Beast/blob/999e2fa0318b5982736d3ea01a418770ea802671/test/websocket/websocket_sync_echo_peer.hpp

Hope this helps!

**Comment by vinniefalco** [comment] 2016-07-08 00:44
I'm going to close this since it is not a bug

**Closed by vinniefalco** 2016-07-08 00:44 UTC
